version: "0.1"
services:
  golang:
    build: ./golang
    ports:
      - "8088:8088"
    links:
      - "mysql"
      - "redis"
    volumes:
      - $HOME/www/code/go-study/code:/go
    tty: true
  mysql:
    image: mysql:5.7
    ports:
      - "3306:33066"
    volumes:
      -   /home/pfinal/www/code/go-study/data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: redis
    ports:
      - "6379:63791"   